import type { Metadata } from 'next'
import './globals.css'
import RealtimeProviders from '@/components/base/realtime-provider'
import { TailwindIndicator } from '@/components/base/tailwind-indicator'
import { ThemeProvider } from '@/components/base/theme-provider'
// import { Toaster } from '@/components/ui/sonner'
import { fraunces, merriweatherSans, mono } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          merriweatherSans.variable,
          fraunces.variable,
          mono.variable,
          'bg-background font-mono text-foreground antialiased',
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="mx-auto w-full max-w-7xl px-4 md:px-6 lg:px-8">
            <RealtimeProviders>{children}</RealtimeProviders>
            <TailwindIndicator />
          </main>
          {/* <Toaster closeButton /> */}
        </ThemeProvider>
      </body>
    </html>
  )
}
